TVShowsNetworks/Models/TVnetwork.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShowsNetworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TVnetwork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVnetwork()
        {
            this.TVshows = new HashSet<TVshow>();
        }
    
        public int NetworkID { get; set; }
        [Display(Name = "Network")]
        public string Name { get; set; }
        public string Logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVshow> TVshows { get; set; }
    }
}

TVShowsNetworks/Controllers/TVnetworksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TVShowsNetworks.Models;

namespace TVShowsNetworks.Controllers
{
    public class TVnetworksController : Controller
    {
        private TVShowsNetworksEntities db = new TVShowsNetworksEntities();

        // GET: TVnetworks
        public ActionResult Index(string searchString)/*implementing search bar*/
        {
            var students = from Name in db.TVnetworks select Name;

            if(searchString != null)
            {
                return View(db.TVnetworks.Where(x => x.Name.StartsWith(searchString)).ToList());
            }
            else
            {
                return View(db.TVnetworks.ToList());
            }
            
        }

        // GET: TVnetworks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TVnetwork tVnetwork = db.TVnetworks.Find(id);
            if (tVnetwork == null)
            {
                return HttpNotFound();
            }
            return View(tVnetwork);
        }

        // GET: TVnetworks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TVnetworks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NetworkID,Name,Logo")] TVnetwork tVnetwork)
        {
            if (ModelState.IsValid)
            {
                db.TVnetworks.Add(tVnetwork);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tVnetwork);
        }

        // GET: TVnetworks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TVnetwork tVnetwork = db.TVnetworks.Find(id);
            if (tVnetwork == null)
            {
                return HttpNotFound();
            }
            return View(tVnetwork);
        }

        // POST: TVnetworks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NetworkID,Name,Logo")] TVnetwork tVnetwork)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tVnetwork).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tVnetwork);
        }

        // GET: TVnetworks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TVnetwork tVnetwork = db.TVnetworks.Find(id);
            if (tVnetwork == null)
            {
                return HttpNotFound();
            }
            return View(tVnetwork);
        }

        // POST: TVnetworks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TVnetwork tVnetwork = db.TVnetworks.Find(id);
            db.TVnetworks.Remove(tVnetwork);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TVShowsNetworks/Views/TVnetworks/Create.cshtml
@model TVShowsNetworks.Models.TVnetwork

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TVnetwork</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TVShowsNetworks/Views/TVnetworks/Delete.cshtml
@model TVShowsNetworks.Models.TVnetwork

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TVnetwork</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TVShowsNetworks/Views/TVnetworks/Details.cshtml
@model TVShowsNetworks.Models.TVnetwork

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TVnetwork</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NetworkID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TVShowsNetworks/Views/TVnetworks/Edit.cshtml
@model TVShowsNetworks.Models.TVnetwork

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TVnetwork</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NetworkID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TVShowsNetworks/Views/TVnetworks/Index.cshtml
@model IEnumerable<TVShowsNetworks.Models.TVnetwork>

@{
    ViewBag.Title = "Index";
}

<h2>TV Networks</h2>


@using (Html.BeginForm("Index", "TVnetwork", FormMethod.Get))
{
    <p>
        <b>Search by Network</b>
        <br />
        @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}


<p>
    @Html.ActionLink("Reset", "Index", "TVnetworks")
</p>

@foreach (var item in Model)
{
    using (Html.BeginForm("Index", "Shows", FormMethod.Get))
    {
        <div>
            <div class="col-sm-6 col-md-4">
                    <input type="hidden" name="network" value=@item.NetworkID>
                    <input type="image" src="@Html.DisplayFor(modelItem => item.Logo)" alt="Logo Photo" class="img-thumbnail network" />
            </div>
        </div>
    }
}


<!--
<ul class="item">
    <li class="col-xs-6 col-md-3">
        <div class="img-thumbnail"></div>
            <img src="@Html.DisplayNameFor(model => model.Logo)" alt="...">
    </li>
-->
<!--
<div class="item">
    <div>
        <div>
            @Html.DisplayNameFor(model => model.Logo)
        </div>
        <div>
            @Html.DisplayNameFor(model => model.Name)
        </div>
    </div>
    
@foreach (var item in Model) {
    <li>
        <div>
            <img src="@Html.DisplayFor(modelItem => item.Logo)" alt="" class="img-thumbnail small-thumbnail" />
        </div>
        
    </li>
}

</ul>
    -->